default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-dbt
      user: dbtuser
      pass: pssd
      port: 5432
      dbname: dbtdb
      schema: dbt
      threads: 4

spark:
  target: local
  outputs:
    local:
      type: spark
      method: thrift
      host: spark-master
      port: 10000
      user: hive
      schema: dbtdb
      connect_retries: 5
      connect_timeout: 60
      retry_all: true