default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-dbt
      user: dbtuser
      pass: pssd
      port: 5432
      dbname: dbtdb
      schema: dbt
      threads: 4

spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      schema: [database/schema name]
      host: [hostname]
      
      # optional
      port: [port]              # default 10001
      user: [user]
      auth: [e.g. KERBEROS]
      kerberos_service_name: [e.g. hive]