version: 2

sources:
  - name: instacart_raw_data
    # no database on sparksql
    # database: dbtdb 
    schema: sample
    tables:
      - name: aisles
      - name: departments
      - name: orders
      - name: products
      - name: order_products__train
      - name: order_products__prior
