version: 2

sources:
  - name: instacart_raw
    # no database on sparksql
    # database: dbtdb 
    schema: source
    tables:
      - name: aisles
      - name: departments
      - name: orders
      - name: products
      - name: order_products
      - name: order_products_new

models:
  - name: stg_orders
    description: "Customer order table"
    schema: sample
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
            - unique
            - not_null
  - name: stg_order_products
    description: "Order product details with joining all related dimensions"
    schema: sample
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
            - not_null
      - name: product_id
        description: "The primary key for this table"
        tests:
            - not_null
  - name: order_products
    description: "Order product details with joining all related dimensions"
    schema: sample
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - product_id
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
            - not_null
      - name: product_id
        description: "The primary key for this table"
        tests:
            - not_null