FROM python:3.7
RUN pip install markupsafe==2.0.1 \
    pip install wtforms==2.3.3 && \
    pip install dbt-postgres==1.1.0 && \
    pip install dbt-rpc==0.1.2

COPY scripts/dbt_init.sh /root/init.sh
RUN chmod +x /root/init.sh

ENTRYPOINT [ "/root/init.sh" ]
