FROM python:3.7
RUN pip install 'apache-airflow==2.3.0' && \
    pip install 'apache-airflow[postgres]==2.3.0'

RUN mkdir /project
COPY scripts_airflow/ /project/scripts/
RUN chmod +x /project/scripts/init.sh

ENTRYPOINT [ "/project/scripts/init.sh" ]
