FROM python:3.7
RUN pip install 'apache-airflow==2.1.2' && \
    pip install 'apache-airflow[postgres]==2.1.2'

RUN mkdir /project
COPY scripts_airflow/ /project/scripts/
RUN chmod +x /project/scripts/init.sh

ENTRYPOINT [ "/project/scripts/init.sh" ]
