FROM apache/airflow:2.3.0
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install --user apache-airflow-providers-postgres==4.1.0


## # Authorize SSH Host

## RUN mkdir -p /home/airflow/.ssh
## RUN chmod 700 /home/airflow/.ssh
## 
## COPY ./key/id_rsa  /home/airflow/.ssh/id_rsa
## RUN chown -R airflow /home/airflow/.ssh
## RUN chmod 600 /home/airflow/.ssh/id_rsa
## 
## COPY ./key/id_rsa  /root/.ssh/id_rsa
## RUN chmod 600 /root/.ssh/id_rsa

USER root
ADD ./scripts/airflow_init.sh $AIRFLOW_HOME/init-scripts/run.sh
RUN chmod -R 755 $AIRFLOW_HOME/init-scripts

USER airflow
