FROM apache/airflow:2.3.0

USER root
## RUN apt-get update && apt-get install -y sasl2-bin libsasl2-2 libsasl2-dev libsasl2-modules libsasl2-modules-gssapi-mit 
RUN apt-get update && apt-get install -y libsasl2-dev gcc g++

USER airflow
RUN pip install --user --upgrade pip wheel setuptools 
RUN pip install --user apache-airflow-providers-postgres==4.1.0 && \
	pip install --user apache-airflow-providers-apache-hive==3.0.0

## Required library for pyhive 
RUN pip install --user sqlalchemy  && \
	pip install --user pyhive  && \
	pip install --user thrift  && \
	pip install --user sasl  && \
	pip install --user thrift-sasl 

## # Authorize SSH Host

## RUN mkdir -p /home/airflow/.ssh
## RUN chmod 700 /home/airflow/.ssh
## 
## COPY ./key/id_rsa  /home/airflow/.ssh/id_rsa
## RUN chown -R airflow /home/airflow/.ssh
## RUN chmod 600 /home/airflow/.ssh/id_rsa
## 
## COPY ./key/id_rsa  /root/.ssh/id_rsa
## RUN chmod 600 /root/.ssh/id_rsa

USER root
ADD ./scripts/airflow_init.sh $AIRFLOW_HOME/init-scripts/run.sh
RUN chmod -R 755 $AIRFLOW_HOME/init-scripts

USER airflow
